### ISSUE TITLE
Click coordinates need to change after resize

### ISSUE THREAD

**Issue by 4silvertooth** [noartem/elementor#20]
In example-gallery if you click `+` button to zoom and without moving cursor if you keep on clicking it responses as though clicking that button, as soon as you move the cursor the coordinates are reset. Same with example-gallery > Button if you click on `Click on me...` at the `right most edge`, even though the button size changes, we can still click it even if the cursor is not on that button.

![test-click](https://user-images.githubusercontent.com/793967/217756089-806b572f-a74f-4cd8-934f-967c74efb8a7.gif)

**Comment by noartem** [comment]
Thank you for reporting this issue!

Recently, I have made significant changes to the hovering feature in our application. Previously, the hovering behavior was controlled directly by the `Hover` element. However, I have refactored the code so that the hovering is now managed by the `Application` itself. This architectural change has resulted in improved performance and behavior, although some bugs still need to be addressed.

Additionally, I have observed that after the refactoring, the hovering functionality appears to work correctly after clicking on this button  :partying_face:
